//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Este código-fonte foi gerado automaticamente por Microsoft.VSDesigner, Versão 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace regin_app_movel.WsControleRequerimento {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WsControleRequerimentoSoap", Namespace="http://tempuri.org/")]
    public partial class WsControleRequerimento : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetXmlRequerimentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetXmlProtocoloOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetStatusProcessoOperationCompleted;
        
        private System.Threading.SendOrPostCallback EncontraAtoEventoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WsControleRequerimento() {
            this.Url = global::regin_app_movel.Properties.Settings.Default.regin_app_movel_WsControleRequerimento_WsControleRequerimento;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetXmlRequerimentoCompletedEventHandler GetXmlRequerimentoCompleted;
        
        /// <remarks/>
        public event GetXmlProtocoloCompletedEventHandler GetXmlProtocoloCompleted;
        
        /// <remarks/>
        public event GetStatusProcessoCompletedEventHandler GetStatusProcessoCompleted;
        
        /// <remarks/>
        public event EncontraAtoEventoCompletedEventHandler EncontraAtoEventoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetXmlRequerimento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode GetXmlRequerimento(string protocolo) {
            object[] results = this.Invoke("GetXmlRequerimento", new object[] {
                        protocolo});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void GetXmlRequerimentoAsync(string protocolo) {
            this.GetXmlRequerimentoAsync(protocolo, null);
        }
        
        /// <remarks/>
        public void GetXmlRequerimentoAsync(string protocolo, object userState) {
            if ((this.GetXmlRequerimentoOperationCompleted == null)) {
                this.GetXmlRequerimentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetXmlRequerimentoOperationCompleted);
            }
            this.InvokeAsync("GetXmlRequerimento", new object[] {
                        protocolo}, this.GetXmlRequerimentoOperationCompleted, userState);
        }
        
        private void OnGetXmlRequerimentoOperationCompleted(object arg) {
            if ((this.GetXmlRequerimentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetXmlRequerimentoCompleted(this, new GetXmlRequerimentoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetXmlProtocolo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetXmlProtocolo(string protocolo) {
            object[] results = this.Invoke("GetXmlProtocolo", new object[] {
                        protocolo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetXmlProtocoloAsync(string protocolo) {
            this.GetXmlProtocoloAsync(protocolo, null);
        }
        
        /// <remarks/>
        public void GetXmlProtocoloAsync(string protocolo, object userState) {
            if ((this.GetXmlProtocoloOperationCompleted == null)) {
                this.GetXmlProtocoloOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetXmlProtocoloOperationCompleted);
            }
            this.InvokeAsync("GetXmlProtocolo", new object[] {
                        protocolo}, this.GetXmlProtocoloOperationCompleted, userState);
        }
        
        private void OnGetXmlProtocoloOperationCompleted(object arg) {
            if ((this.GetXmlProtocoloCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetXmlProtocoloCompleted(this, new GetXmlProtocoloCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetStatusProcesso", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetStatusProcesso(string protocolo) {
            object[] results = this.Invoke("GetStatusProcesso", new object[] {
                        protocolo});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetStatusProcessoAsync(string protocolo) {
            this.GetStatusProcessoAsync(protocolo, null);
        }
        
        /// <remarks/>
        public void GetStatusProcessoAsync(string protocolo, object userState) {
            if ((this.GetStatusProcessoOperationCompleted == null)) {
                this.GetStatusProcessoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStatusProcessoOperationCompleted);
            }
            this.InvokeAsync("GetStatusProcesso", new object[] {
                        protocolo}, this.GetStatusProcessoOperationCompleted, userState);
        }
        
        private void OnGetStatusProcessoOperationCompleted(object arg) {
            if ((this.GetStatusProcessoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStatusProcessoCompleted(this, new GetStatusProcessoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EncontraAtoEvento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet EncontraAtoEvento(string cnpjOrgao, string protocoloReq) {
            object[] results = this.Invoke("EncontraAtoEvento", new object[] {
                        cnpjOrgao,
                        protocoloReq});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void EncontraAtoEventoAsync(string cnpjOrgao, string protocoloReq) {
            this.EncontraAtoEventoAsync(cnpjOrgao, protocoloReq, null);
        }
        
        /// <remarks/>
        public void EncontraAtoEventoAsync(string cnpjOrgao, string protocoloReq, object userState) {
            if ((this.EncontraAtoEventoOperationCompleted == null)) {
                this.EncontraAtoEventoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEncontraAtoEventoOperationCompleted);
            }
            this.InvokeAsync("EncontraAtoEvento", new object[] {
                        cnpjOrgao,
                        protocoloReq}, this.EncontraAtoEventoOperationCompleted, userState);
        }
        
        private void OnEncontraAtoEventoOperationCompleted(object arg) {
            if ((this.EncontraAtoEventoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EncontraAtoEventoCompleted(this, new EncontraAtoEventoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetXmlRequerimentoCompletedEventHandler(object sender, GetXmlRequerimentoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetXmlRequerimentoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetXmlRequerimentoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetXmlProtocoloCompletedEventHandler(object sender, GetXmlProtocoloCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetXmlProtocoloCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetXmlProtocoloCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetStatusProcessoCompletedEventHandler(object sender, GetStatusProcessoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStatusProcessoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetStatusProcessoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void EncontraAtoEventoCompletedEventHandler(object sender, EncontraAtoEventoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EncontraAtoEventoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EncontraAtoEventoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591